class Main{
    public static void main(String[] args){
        // byte b=-128;
        // float b=10.0f;
        // char b='/u ahdd';
        // char b=65;
        // char b='z';
        
        // int i=90;
        // char c=(char)i;
        
        // char c='9';
        // int i=(c-48)*10;
        
        // char c=90;
        // byte b=c;**
        // byte b='a';
        
        // int b=0b1010;
        int b=012;
        // int b=0xa;
        System.out.print(b);
    }
}
